// {{NAME}} — generated by `akamata init {{NAME}}`.
//
// One file is enough to demo the modern model + handler workflow. Move things
// into separate files (models.zig, handlers.zig, setup.zig) as the app grows.

const std = @import("std");
const am = @import("akamata");

// ===== Model =====================================================
//
// Define a struct with a `__schema` block to get a typed table + a Repo with
// `.find / .all / .where / .create / .save / .delete`. See docs/en/handbook.md
// for indexes, defaults, validators, and relations.

pub const Note = struct {
    id: ?i64 = null,
    title: []const u8,
    body: []const u8,
    created_at: ?i64 = null,

    pub const __schema = .{
        .table = "notes",
        .primary_key = "id",
        .defaults = .{
            .created_at = "unixepoch()",
        },
        .validates = .{
            .title = .{ am.model.rule.required, am.model.rule.max_len(120) },
            .body = .{ am.model.rule.required, am.model.rule.max_len(4096) },
        },
    };
};

const Notes = am.model.repo(Note);

// ===== App state =================================================
//
// `db` is special-cased by `c.db()` (and `c.cfg()` if you add config). The
// model-aware migrator walks `all_models` to keep the schema in sync.

pub const State = struct {
    db: am.db.Db,
};

pub const all_models = [_]am.model.TableDef{
    am.model.tableDef(Note),
};

// ===== Handlers ==================================================

const Ctx = am.Context(State);

fn index(c: *Ctx) !void {
    try c.json(.{
        .name = "{{NAME}}",
        .endpoints = .{
            .health = "GET /health",
            .list = "GET /notes",
            .create = "POST /notes  { title, body }",
            .show = "GET /notes/:id",
            .delete = "DELETE /notes/:id",
        },
    }, 200);
}

fn health(c: *Ctx) !void {
    var stmt = c.db().prepare("SELECT 1") catch return c.serverError("db unavailable");
    defer stmt.deinit();
    _ = stmt.step() catch return c.serverError("db unavailable");
    try c.json(.{ .status = "ok" }, 200);
}

fn listNotes(c: *Ctx) !void {
    const notes = try Notes.all(c.db(), c.arena);
    try c.json(.{ .notes = notes }, 200);
}

fn createNote(c: *Ctx) !void {
    const note = (try c.input(Note)) orelse return;
    const created = try Notes.create(c.db(), c.arena, note);
    try c.json(created, 201);
}

fn showNote(c: *Ctx) !void {
    const id = c.req.paramAs(i64, "id") catch return c.badRequest("invalid id");
    const n = (try Notes.find(c.db(), c.arena, id)) orelse return c.notFound();
    try c.json(n, 200);
}

fn deleteNote(c: *Ctx) !void {
    const id = c.req.paramAs(i64, "id") catch return c.badRequest("invalid id");
    try Notes.delete(c.db(), id);
    try c.json(.{ .deleted = id }, 200);
}

// ===== Wiring ====================================================

pub fn registerRoutes(app: *am.App(State)) !void {
    _ = try app.useAll(am.mw.recover(State));
    _ = try app.useAll(am.mw.logger(State));

    _ = try app.get("/", index);
    _ = try app.get("/health", health);
    _ = try app.get("/notes", listNotes);
    _ = try app.post("/notes", createNote);
    _ = try app.get("/notes/:id", showNote);
    _ = try app.delete("/notes/:id", deleteNote);
}

pub fn buildState(alloc: std.mem.Allocator) !State {
    if (am.backend == .native) am.env.loadDotEnv(alloc, ".env") catch {};
    const url = am.env.get(alloc, "DATABASE_URL") orelse
        try alloc.dupe(u8, if (am.backend == .native) "file:{{NAME}}.db" else "d1:DB");
    defer alloc.free(url);
    const database = try am.db.open(alloc, url);
    if (am.backend == .native) {
        var arena_state: std.heap.ArenaAllocator = .init(alloc);
        defer arena_state.deinit();
        const plan = am.model.migrate.diff(arena_state.allocator(), database, &all_models) catch |e| {
            std.log.warn("migrate.diff: {t}", .{e});
            return .{ .db = database };
        };
        am.model.migrate.apply(arena_state.allocator(), database, plan) catch |e| {
            std.log.warn("migrate.apply: {t}", .{e});
        };
    }
    return .{ .db = database };
}

fn migrateUp(alloc: std.mem.Allocator, args: []const [:0]const u8) !void {
    var dir: []const u8 = "migrations";
    var target: ?[]const u8 = null;
    for (args) |raw| {
        const arg = std.mem.sliceTo(raw, 0);
        if (std.mem.startsWith(u8, arg, "--dir=")) dir = arg[6..] else if (std.mem.startsWith(u8, arg, "--target=")) target = arg[9..] else {
            std.debug.print("migrate-up: unknown option `{s}`\n", .{arg});
            return error.InvalidMigrationOption;
        }
    }

    am.env.loadDotEnv(alloc, ".env") catch {};
    const url = am.env.get(alloc, "DATABASE_URL") orelse try alloc.dupe(u8, "file:{{NAME}}.db");
    defer alloc.free(url);

    var arena_state: std.heap.ArenaAllocator = .init(alloc);
    defer arena_state.deinit();
    const arena = arena_state.allocator();
    const database = try am.db.open(alloc, url);
    defer database.close();

    const all = am.model.migrate.loadMigrationsFromDir(arena, dir) catch |err| {
        if (err == error.MigrationsDirNotFound) {
            std.debug.print("migrate-up: directory `{s}` does not exist\n", .{dir});
        }
        return err;
    };
    const migrator: am.model.migrate.Migrator = .{ .arena = arena, .db = database };
    const pending = try migrator.pending(all);

    var selected: std.ArrayList(am.model.migrate.Migration) = .empty;
    for (pending) |migration| {
        if (target) |limit| {
            if (std.mem.order(u8, migration.version, limit) == .gt) continue;
        }
        try selected.append(arena, migration);
    }
    if (selected.items.len == 0) {
        std.log.info("migrate-up: nothing pending ({d} migration file(s))", .{all.len});
        return;
    }
    for (selected.items) |migration| std.log.info("applying {s}", .{migration.name});
    try migrator.applyAll(selected.items);
    std.log.info("applied {d} migration(s)", .{selected.items.len});
}

pub fn main(init: std.process.Init) !void {
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const alloc = gpa.allocator();

    var args_arena: std.heap.ArenaAllocator = .init(alloc);
    defer args_arena.deinit();
    const args = try init.minimal.args.toSlice(args_arena.allocator());
    if (args.len >= 2 and std.mem.eql(u8, std.mem.sliceTo(args[1], 0), "migrate-up")) {
        return migrateUp(alloc, args[2..]);
    }

    var app = am.App(State).init(alloc, try buildState(alloc));
    defer app.deinit();
    defer app.state().db.close();
    try registerRoutes(&app);

    const port_env = am.env.get(alloc, "PORT");
    defer if (port_env) |p| alloc.free(p);
    const port: u16 = if (port_env) |p| std.fmt.parseInt(u16, p, 10) catch 8080 else 8080;

    std.log.info("{{NAME}} listening on :{d}", .{port});
    try app.serve(.{ .port = port });
}
