// {{NAME}} — generated by `akamata init {{NAME}}`.
//
// One file is enough to demo the modern model + handler workflow. Move things
// into separate files (models.zig, handlers.zig, setup.zig) as the app grows.

const std = @import("std");
const am = @import("akamata");

// ===== Model =====================================================
//
// Define a struct with a `__schema` block to get a typed table + a Repo with
// `.find / .all / .where / .create / .save / .delete`. See docs/handbook.md
// for indexes, defaults, validators, and relations.

pub const Note = struct {
    id: ?i64 = null,
    title: []const u8,
    body: []const u8,
    created_at: ?i64 = null,

    pub const __schema = .{
        .table = "notes",
        .primary_key = "id",
        .defaults = .{
            .created_at = "unixepoch()",
        },
        .validates = .{
            .title = .{ am.model.rule.required, am.model.rule.max_len(120) },
            .body  = .{ am.model.rule.required, am.model.rule.max_len(4096) },
        },
    };
};

const Notes = am.model.repo(Note);

// ===== App state =================================================
//
// `db` is special-cased by `c.db()` (and `c.cfg()` if you add config). The
// model-aware migrator walks `all_models` to keep the schema in sync.

pub const State = struct {
    db: am.db.Db,
};

pub const all_models = [_]am.model.TableDef{
    am.model.tableDef(Note),
};

// ===== Handlers ==================================================

const Ctx = am.Context(State);

fn index(c: *Ctx) !void {
    try c.json(.{
        .name = "{{NAME}}",
        .endpoints = .{
            .health = "GET /health",
            .list = "GET /notes",
            .create = "POST /notes  { title, body }",
            .show = "GET /notes/:id",
            .delete = "DELETE /notes/:id",
        },
    }, 200);
}

fn health(c: *Ctx) !void {
    var stmt = c.db().prepare("SELECT 1") catch return c.serverError("db unavailable");
    defer stmt.deinit();
    _ = stmt.step() catch return c.serverError("db unavailable");
    try c.json(.{ .status = "ok" }, 200);
}

fn listNotes(c: *Ctx) !void {
    const notes = try Notes.all(c.db(), c.arena);
    try c.json(.{ .notes = notes }, 200);
}

fn createNote(c: *Ctx) !void {
    const note = (try c.input(Note)) orelse return;
    const created = try Notes.create(c.db(), c.arena, note);
    try c.json(created, 201);
}

fn showNote(c: *Ctx) !void {
    const id = c.req.paramAs(i64, "id") catch return c.badRequest("invalid id");
    const n = (try Notes.find(c.db(), c.arena, id)) orelse return c.notFound();
    try c.json(n, 200);
}

fn deleteNote(c: *Ctx) !void {
    const id = c.req.paramAs(i64, "id") catch return c.badRequest("invalid id");
    try Notes.delete(c.db(), id);
    try c.json(.{ .deleted = id }, 200);
}

// ===== Wiring ====================================================

pub fn registerRoutes(app: *am.App(State)) !void {
    _ = try app.useAll(am.mw.recover(State));
    _ = try app.useAll(am.mw.logger(State));

    _ = try app.get("/", index);
    _ = try app.get("/health", health);
    _ = try app.get("/notes", listNotes);
    _ = try app.post("/notes", createNote);
    _ = try app.get("/notes/:id", showNote);
    _ = try app.delete("/notes/:id", deleteNote);
}

pub fn buildState(alloc: std.mem.Allocator) !State {
    if (am.backend == .native) am.env.loadDotEnv(alloc, ".env") catch {};
    const url = am.env.get(alloc, "DATABASE_URL") orelse
        try alloc.dupe(u8, if (am.backend == .native) "file:{{NAME}}.db" else "d1:DB");
    const database = try am.db.open(alloc, url);
    if (am.backend == .native) {
        var arena_state: std.heap.ArenaAllocator = .init(alloc);
        defer arena_state.deinit();
        const plan = am.model.migrate.diff(arena_state.allocator(), database, &all_models) catch |e| {
            std.log.warn("migrate.diff: {t}", .{e});
            return .{ .db = database };
        };
        am.model.migrate.apply(arena_state.allocator(), database, plan) catch |e| {
            std.log.warn("migrate.apply: {t}", .{e});
        };
    }
    return .{ .db = database };
}

pub fn main() !void {
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const alloc = gpa.allocator();

    var app = am.App(State).init(alloc, try buildState(alloc));
    defer app.deinit();
    try registerRoutes(&app);

    const port_env = am.env.get(alloc, "PORT");
    defer if (port_env) |p| alloc.free(p);
    const port: u16 = if (port_env) |p| std.fmt.parseInt(u16, p, 10) catch 8080 else 8080;

    std.log.info("{{NAME}} listening on :{d}", .{port});
    try app.serve(.{ .port = port });
}
