//! Lightweight realtime/embedded client generation from one Zig tagged union.
const std = @import("std");
const events = @import("events.zig");

pub const Target = enum { typescript, c };
pub const Options = struct { target: Target, name: []const u8 = "AkamataEvent", version: u16 = 1 };

pub fn generate(comptime EventUnion: type, allocator: std.mem.Allocator, options: Options) ![]u8 {
    events.validateProtocol(EventUnion);
    var aw: std.Io.Writer.Allocating = .init(allocator);
    errdefer aw.deinit();
    switch (options.target) {
        .typescript => try emitTypescript(EventUnion, &aw.writer, options),
        .c => try emitC(EventUnion, &aw.writer, options),
    }
    return aw.toOwnedSlice();
}

fn emitTypescript(comptime U: type, w: *std.Io.Writer, options: Options) !void {
    try w.writeAll("// Generated by Akamata. Do not edit.\n");
    inline for (@typeInfo(U).@"union".fields) |field| {
        try w.print("export interface {s}Payload ", .{title(field.name)});
        try writeTsType(field.type, w);
        try w.writeAll("\n");
    }
    try w.print("export type {s} =\n", .{options.name});
    inline for (@typeInfo(U).@"union".fields, 0..) |field, i| {
        try w.print("  {s} {{ event_type: \"{s}\"; payload: {s}Payload }}\n", .{ if (i == 0) "=" else "|", field.name, title(field.name) });
    }
    try w.print("export interface AkamataEnvelope<T extends {s} = {s}> {{ protocol_version: {d}; event_id?: string; correlation_id?: string; event: T }}\n", .{ options.name, options.name, options.version });
    try w.writeAll(
        "export function connectAkamata(url: string, onEvent: (event: AkamataEnvelope) => void): WebSocket {\n" ++
            "  const ws = new WebSocket(url); ws.addEventListener(\"message\", e => onEvent(JSON.parse(String(e.data)))); return ws;\n}\n",
    );
}

fn emitC(comptime U: type, w: *std.Io.Writer, options: Options) !void {
    try w.writeAll("/* Generated by Akamata. Types and protocol metadata only. */\n#pragma once\n#include <stdint.h>\n#include <stddef.h>\n");
    try w.print("#define AKAMATA_PROTOCOL_VERSION {d}\n", .{options.version});
    try w.writeAll("typedef enum akamata_event_kind {\n");
    inline for (@typeInfo(U).@"union".fields, 0..) |field, i| try w.print("  AKAMATA_EVENT_{s} = {d},\n", .{ upper(field.name), i });
    try w.writeAll("} akamata_event_kind;\n");
    inline for (@typeInfo(U).@"union".fields) |field| {
        if (@typeInfo(field.type) != .@"struct") continue;
        try w.print("typedef struct akamata_{s}_payload {{\n", .{field.name});
        inline for (@typeInfo(field.type).@"struct".fields) |member| {
            try writeCField(member.type, member.name, w);
        }
        try w.print("}} akamata_{s}_payload;\n", .{field.name});
    }
    try w.writeAll("typedef struct akamata_envelope_meta { uint16_t protocol_version; akamata_event_kind event_type; const char *event_id; const char *correlation_id; } akamata_envelope_meta;\n");
}

fn writeTsType(comptime T: type, w: *std.Io.Writer) !void {
    switch (@typeInfo(T)) {
        .@"struct" => |s| {
            try w.writeAll("{");
            inline for (s.fields) |field| {
                try w.print(" {s}: ", .{field.name});
                try writeTsType(field.type, w);
                try w.writeAll(";");
            }
            try w.writeAll(" }");
        },
        .int, .float => try w.writeAll("number"),
        .bool => try w.writeAll("boolean"),
        .@"enum" => |e| inline for (e.fields, 0..) |field, i| try w.print("{s}\"{s}\"", .{ if (i == 0) "" else " | ", field.name }),
        .pointer => |p| if (p.size == .slice and p.child == u8) try w.writeAll("string") else try w.writeAll("unknown[]"),
        .array => try w.writeAll("number[]"),
        .optional => |o| {
            try writeTsType(o.child, w);
            try w.writeAll(" | null");
        },
        else => try w.writeAll("unknown"),
    }
}

fn writeCField(comptime T: type, comptime name: []const u8, w: *std.Io.Writer) !void {
    switch (@typeInfo(T)) {
        .int => |i| try w.print("  {s}{d}_t {s};\n", .{ if (i.signedness == .signed) "int" else "uint", normalizedBits(i.bits), name }),
        .float => |f| try w.print("  {s} {s};\n", .{ if (f.bits <= 32) "float" else "double", name }),
        .bool => try w.print("  uint8_t {s};\n", .{name}),
        .array => |a| if (a.child == u8) try w.print("  uint8_t {s}[{d}];\n", .{ name, a.len }) else try w.print("  /* unsupported array element */ uint8_t {s}[{d}];\n", .{ name, a.len }),
        .pointer => |p| if (p.size == .slice and p.child == u8) try w.print("  const char *{s}; size_t {s}_len;\n", .{ name, name }) else try w.print("  /* unsupported pointer: {s} */ void *{s};\n", .{ @typeName(T), name }),
        .@"enum" => try w.print("  int32_t {s};\n", .{name}),
        else => try w.print("  /* unsupported field type: {s} */ uint8_t {s};\n", .{ @typeName(T), name }),
    }
}

fn normalizedBits(bits: u16) u16 {
    return if (bits <= 8) 8 else if (bits <= 16) 16 else if (bits <= 32) 32 else 64;
}
fn title(comptime value: []const u8) []const u8 {
    return value;
}
fn upper(comptime value: []const u8) []const u8 {
    return value;
}

test "generate TypeScript and C realtime clients" {
    const E = union(enum) { created: struct { id: u64, name: []const u8 }, closed: struct { code: u16 } };
    const ts = try generate(E, std.testing.allocator, .{ .target = .typescript, .version = 2 });
    defer std.testing.allocator.free(ts);
    try std.testing.expect(std.mem.indexOf(u8, ts, "event_type: \"created\"") != null);
    const c = try generate(E, std.testing.allocator, .{ .target = .c, .version = 2 });
    defer std.testing.allocator.free(c);
    try std.testing.expect(std.mem.indexOf(u8, c, "AKAMATA_PROTOCOL_VERSION 2") != null);
}
